### ISSUE TITLE
August (updating ongoing issues)

### ISSUE THREAD

**Issue by AdyanRios-NOAA** [AdyanRios-NOAA/SEFSC-MH-Processing#88]
- Find out percent of database that processing is working (except multi reg) #79 
    - 7884 records, among 2100 Clusters
    - 400 clusters with multi-regs (19%)
    - 80% believed to be processing correctly and sorting in the same way they had to be manually sorted for the documents we have created so far
- Database oddities
     - Multi-reg (20% of Clusters)
     - Additional spot checks related to species with different fishing years (we think this is redundant wand working but to be sure)
     - Investigate delays #5
     - Endorsement related issues #20
     - Finalize static clusters
     - Do we expect species list changes (technically our dataset links to another dataset)
- Where to publish (peer review) conversation #85 
- ODM Disclaimer (likely to come from conversations with SERO, also, find examples of other open source disclaimers)
- How to make processed database accessible (database package to R, with versioning, and open access code of processing ODM)
- Review data user and data manager user manuals #83 
- Spanish Mackerel (initiate document review, cross check email with SEDAR history provider) #76
- Bugs with Yanet #80 
    - Phase out bug processing 0B
- SERO planning #84
    - [x] Schedule dry run

Action Items
- [x] Action item: fix validation in ODM #80
- [x] Action item: Merge in processing branch to main branch, create new branch for clean up
- [x] Start revisualizing output dataframe to be more similar to the formats we have already been publishing #74
- [x] Discuss updating processing metadata #75
- [x] Clean up issues

**Comment by AdyanRios-NOAA** [comment]
- Delays are another type oddities (15 clusters, not main management types) 
- Spanish Mackerel: do we need to provide full cross check to providers of the excel version? There are fairly extensive differences, and we are confident we have incorporated information correctly into MH.

**Comment by AdyanRios-NOAA** [comment]
Should we still only do the species expansion for detailed?
Add other FMPs to [Zone_name_xref](https://docs.google.com/spreadsheets/d/1gVFz6UUiN5LU3Fr9NuFSumKGeHvRubgZviJt7R73Gvg/edit#gid=0)
Look for a cluster with a recurring regulation (Red Snapper Cluster 20)
Look for a cluster with a delay (Cluster 114 and 115, ALL Snapper Grouper)
Are we actually using lubridate?
A few more records/bugs to resolve to verify and do away with processing bugs in R.

**Comment by AdyanRios-NOAA** [comment]
Also look into an example of withdrawn

**Comment by AdyanRios-NOAA** [comment]
Find out when the Spanish Mackerel WP Deadline is

**Comment by AdyanRios-NOAA** [comment]
Topics to discuss 8/23
- [x] Yanet system updates for SERO demo
- [x] Strategy for Spanish Mackerel (include multiple FMPs? Continue the comparisons to SEDAR provided history?)
- [x] Mention plan for checking bugs/removing data bugs script (next Tuesday, August 30th)
- [x] Two more hours of processing today
    - [x] Finalized code annotation clean up

**Comment by AdyanRios-NOAA** [comment]
Topics to discuss 8/30
